version: "3.8"

services:
  sz-express:
    build:
      context: ./backend
      target: production
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    networks:
      - sz-network
    depends_on:
      - sz-postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sz-postgres:
    image: postgres:16
    container_name: sz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - sz-postgres-data:/var/lib/postgresql/data
    networks:
      - sz-network

  sz-caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}
      - CADDY_EMAIL=${CADDY_EMAIL}
    networks:
      - sz-network

volumes:
  sz-postgres-data:
  caddy_data:
  caddy_config:

networks:
  sz-network:
    driver: bridge
